name: OHC Network - Zoom Drive

on:
  schedule:
    - cron: '0 0 * * 0' # runs every Sunday at 12:00 AM UTC
  workflow_dispatch:
    inputs:
      lookback_days:
        description: Number of days to keep Zoom meeting recordings
        required: false
      end_date:
        description: End date of Zoom meeting recordings to keep (YYYY-MM-DD)
        required: false
      delete_on_success:
        description: 'Delete recordings after uploading to Google Drive'
        required: false
        default: false

jobs:
  zoomdrive:
    runs-on: ubuntu-latest
    environment: Open Healthcare Network
    name: Download Zoom recordings and upload to Google Drive
    steps:
      - name: Download Meetings from Zoom Cloud and Upload to Google Drive
        id: zoomdrive
        uses: coronasafe/zoomdrive@main
        with:
          zoom_account_id: ${{ secrets.ZOOM_ACCOUNT_ID }}
          zoom_client_id: ${{ secrets.ZOOM_CLIENT_ID }}
          zoom_client_secret: ${{ secrets.ZOOM_CLIENT_SECRET }}

          lookback_days: ${{ github.event.inputs.lookback_days || 7 }}
          end_date: ${{ github.event.inputs.end_date }}
          delete_on_success: ${{ github.event.inputs.delete_on_success || false }}

          gsa_credentials: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_CREDENTIALS }}
          meeting_gdrive_folder_map: ${{ secrets.MEETING_GDRIVE_FOLDER_MAP }}
